<a href="https://colab.research.google.com/github/DhruvDekhane62/Deep_Learning_Training/blob/main/DL_Training2_Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implemenation of Logistic Regression(Classification Model)

 "Heart Disease Prediction"

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=pd.read_csv("/content/heart - Copy.csv")

In [ ]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145.0,233,1,0,150.0,0,2.3,0,0,1,1
1,37,1,2,130.0,250,0,1,187.0,0,3.5,0,0,2,1
2,41,0,1,130.0,204,0,0,172.0,0,1.4,2,0,2,1
3,56,1,1,120.0,236,0,1,178.0,0,0.8,2,0,2,1
4,57,0,0,120.0,354,0,1,163.0,1,0.6,2,0,2,1

In [ ]:
data["target"].unique()

array([1, 0])

In [ ]:
data["target"].value_counts()

target
1    170
0    138
Name: count, dtype: int64

In [ ]:
data["target"].value_counts()

target
1    170
0    138
Name: count, dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(6)

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     0
thalach     2
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
#Imputation
data["trestbps"].fillna(data["trestbps"].mean(),inplace=True)
data["thalach"].fillna(data["thalach"].mean(),inplace=True)

In [ ]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
#Extraction of Independent variable & Dependent variable usling (.iloc)

X=data.iloc[:,0:-1]
Y=data.iloc[:, -1:]

In [ ]:
#Data Splitting

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
#Model Creation by Logistic Regression

from sklearn.linear_model import LogisticRegression
lrc=LogisticRegression()
lrc.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
#Prediction or Testing

Y_pred=lrc.predict(X_test)

In [ ]:
#Evaluate the performance of metrics

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

[[24  8]
 [ 3 26]]

In [ ]:
#Accuracy

from sklearn.metrics import accuracy_score
ac=accuracy_score(Y_test,Y_pred)*100
print(ac)

81.9672131147541

In [ ]:
#Precision

from sklearn.metrics import precision_score
ps=precision_score(Y_test,Y_pred)*100
print(ps)

76.47058823529412

In [ ]:
#Recall

from sklearn.metrics import recall_score
rs=recall_score(Y_test,Y_pred)*100
print(rs)

89.65517241379311

In [ ]:
#F1 Score

from sklearn.metrics import f1_score
f1=f1_score(Y_test,Y_pred)*100
print(f1)

82.53968253968253

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.89      0.75      0.81        32
           1       0.76      0.90      0.83        29

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.83      0.82      0.82        61

# Implementation of KNN

In [ ]:
#Data Test Splitting

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
#Create KNN Model

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
#Prediction

Y_pred=knn.predict(X_test)

In [ ]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred)*100)
print(precision_score(Y_test,Y_pred)*100)
print(recall_score(Y_test,Y_pred)*100)
print(f1_score(Y_test,Y_pred)*100)

[[18 16]
 [ 6 21]]
63.934426229508205
56.75675675675676
77.77777777777779
65.625

# Hyperparameter Tunning & Cross Valdation

   * Hyperparameter Tunning is a process of selecting the best or optimal parameter for the model

In [ ]:
#GridSearchCV

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

knnc=KNeighborsClassifier()
grid_param={"n_neighbors":[3,5,7,9],"p":[1,2]}

grid_model=GridSearchCV(knnc, grid_param, cv=5)
grid_model.fit(X_train, Y_train.values.ravel())

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9], 'p': [1, 2]})

In [ ]:
# get the best paramter of the model
grid_model.best_params_

{'n_neighbors': 9, 'p': 1}

In [ ]:
final_model=grid_model.best_estimator_

In [ ]:
Y_pred=final_model.predict(X_test)

In [ ]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred)*100)
print(precision_score(Y_test, Y_pred)*100)
print(recall_score(Y_test, Y_pred)*100)
print(f1_score(Y_test, Y_pred)*100)

[[19 15]
 [ 5 22]]
67.21311475409836
59.45945945945946
81.48148148148148
68.75

  * Bagging Ensemble Model

In [ ]:
#Data Splitting
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
#random Forest Model
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=50)
rfc.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=50)

In [ ]:
Y_pred=rfc.predict(X_test)

In [ ]:
#confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred)*100)
print(precision_score(Y_test, Y_pred)*100)
print(recall_score(Y_test, Y_pred)*100)
print(f1_score(Y_test, Y_pred)*100)

[[24  5]
 [ 8 24]]
78.68852459016394
82.75862068965517
75.0
78.68852459016394

  * Boosting Ensemble Model

In [ ]:
#Gradient Boosting Classification

from sklearn.ensemble import GradientBoostingClassifier
GBC=GradientBoostingClassifier()
GBC.fit(X_train, Y_train)

GradientBoostingClassifier()

In [ ]:
Y_pred=GBC.predict(X_test)

In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred)*100)
print(precision_score(Y_test, Y_pred)*100)
print(recall_score(Y_test, Y_pred)*100)
print(f1_score(Y_test, Y_pred)*100)

[[24  5]
 [10 22]]
75.40983606557377
81.48148148148148
68.75
74.57627118644068

# Dimensionality Reduction -- PCA
  * PCA is Unsupervised Learning approach for Dimensionality Reduction

In [ ]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145.0,233,1,0,150.0,0,2.3,0,0,1
1,37,1,2,130.0,250,0,1,187.0,0,3.5,0,0,2
2,41,0,1,130.0,204,0,0,172.0,0,1.4,2,0,2
3,56,1,1,120.0,236,0,1,178.0,0,0.8,2,0,2
4,57,0,0,120.0,354,0,1,163.0,1,0.6,2,0,2

In [ ]:
print("Shape before applying PCA on X", X.shape)

Shape before applying PCA on X (302, 13)

In [ ]:
#Apply PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X=pca.fit_transform(X)

In [ ]:
print("Shape after applying PCA on X", X.shape)

Shape after applying PCA on X (302, 2)

In [ ]:
#Check the percentage of information repreaented by each component
pca.explained_variance_ratio_*100

array([74.71073089, 15.04888494])